#!/bin/sh
#
# Start aawgd daemon
#

DAEMON="aawgd"
PIDFILE="/var/run/$DAEMON.pid"


RETVAL=0

case "$1" in
	start)
		if [ -z "$AAWG_CONF_SOURCED" ]; then
			echo "Source /etc/aawgd.conf"
			# Export the variables so they reach the supervisor and daemon
			# when this script is invoked directly rather than from rcS
			set -a
			source /etc/aawgd.conf
			set +a
		fi

		printf "Starting $DAEMON: "
		# Run under the supervisor so a crashed daemon restarts in seconds
		start-stop-daemon -S -b -q -m -p "$PIDFILE" -x "/usr/bin/aawgd-supervise"
		RETVAL=$?
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $DAEMON: "
		start-stop-daemon -K -q -p "$PIDFILE"
		RETVAL=$?
		killall -q "$DAEMON"
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop}"
		;;
esac

exit $RETVAL
